# 파이토치 기초

## 텐서 만들기

우선 헬퍼 함수 describe(x) 정의

In [ ]:
def describe(x): # 텐서의 속성 출력
  print("타입: {}".format(x.type())) # 타입
  print("크기: {}".format(x.shape)) # 차원
  print("값: \n{}".format(x)) # 값

### 차원을 지정하여 텐서를 랜덤하게 초기화 하기

In [ ]:
import torch
describe(torch.Tensor(2,3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[9.0935e-36, 0.0000e+00, 1.5695e-43],
        [1.5554e-43, 1.5975e-43, 1.6255e-43]])


### [0,1) 범위의 균등 분포에서 샘플링한 값으로 초기화한 텐서 만들기(표준 정규분포에서 텐서 만들기)

In [ ]:
import torch
describe(torch.rand(2,3)) # 균등 분포
describe(torch.randn(2,3)) # 표준 정규 분포

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.3079, 0.6037, 0.8427],
        [0.8513, 0.7552, 0.7670]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 0.0386,  1.3926,  1.1654],
        [-2.3406, -0.1496, -0.1444]])


### 동일한 스칼라값을 채운 텐서 만들기

In [ ]:
import torch
describe(torch.zeros(2,3))
x = torch.ones(2,3)
describe(x)
x.fill_(5) # 특정값으로 채울 수 있다. 이렇게 밑줄 문자가 있는 '파이 토치 인-플레이스' 메서드는 텐서값을 바꾸는 연산을 뜻한다. 즉, 새로운 객체를 만들지 않고 현재값을 변경한다.
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


### 파이썬 리스트로 텐서 만들기

In [ ]:
x = torch.Tensor([[1, 2, 3], 
                  [4, 5, 6]])
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### 넘파이로 텐서 만들기

In [ ]:
import torch
import numpy as np
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))

타입: torch.DoubleTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.6948, 0.0336, 0.0511],
        [0.6823, 0.4670, 0.6976]], dtype=torch.float64)


타입이 기존 FloatTensor에서 DoubleTensor로 바뀌었다. (넘파이 배열의 기본 데이터 타입이 float64 이기 때문)

## 텐서 타입과 크기

텐서에는 타입과 크기가 있다. torch.Tensor 생성자를 사용한다면 기본 타입은 torch.FloatTensor이다. 텐서 타입은 초기화할 때 지정하거나 나중에 타입 캐스팅(casting) 메서드로 바꿀 수 있다. 

초기화 할 때 타입을 지정하려면 FloatTensor와 LongTensor 같은 특정 텐서 타입의 생성자를 직접 호출하거나 torch.tensor()메서드의 dtype 매개변수를 활용할 수 있다.

In [ ]:
x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
x = x.long()
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
x = torch.tensor([[1,2,3],
                  [4,5,6]], dtype=torch.int64)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
x = x.float()
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


## 텐서 연산

텐서를 만들고 일반적인 프로그래밍 언어처럼 +, -, *, /를 사용해 연산을 수행할 수 있다.

연산자에 대응하는 .add() 같은 함수를 사용해도 된다.

### 텐서 덧셈

In [ ]:
import torch
x = torch.randn(2,3)
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.7010, 0.0123, 0.2258],
        [1.8704, 0.7130, 0.0362]])


In [ ]:
describe(torch.add(x, x))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1.4021, 0.0246, 0.4516],
        [3.7407, 1.4260, 0.0725]])


In [ ]:
describe(x + x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1.4021, 0.0246, 0.4516],
        [3.7407, 1.4260, 0.0725]])


### 차원별 텐서 연산

In [ ]:
import torch
x = torch.arange(6)
describe(x)

타입: torch.LongTensor
크기: torch.Size([6])
값: 
tensor([0, 1, 2, 3, 4, 5])


In [ ]:
x = x.view(2,3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
describe(torch.sum(x, dim=0)) # 같은 열끼리 더하기

타입: torch.LongTensor
크기: torch.Size([3])
값: 
tensor([3, 5, 7])


In [ ]:
describe(torch.sum(x,dim=1)) # 같은 행끼리 더하기

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([ 3, 12])


In [ ]:
describe(torch.transpose(x, 0, 1)) # 행과 열 뒤집기

타입: torch.LongTensor
크기: torch.Size([3, 2])
값: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


## 인덱싱, 슬라이싱, 연결

### 텐서 슬라이싱과 인덱싱

In [ ]:
import torch
x = torch.arange(6).view(2, 3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
describe(x[:1, :2])

타입: torch.LongTensor
크기: torch.Size([1, 2])
값: 
tensor([[0, 1]])


In [ ]:
describe(x[:1, :3])

타입: torch.LongTensor
크기: torch.Size([1, 3])
값: 
tensor([[0, 1, 2]])


In [ ]:
describe(x[:2, :3])

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
describe(x[0, 1])

타입: torch.LongTensor
크기: torch.Size([])
값: 
1


### 복잡한 인덱싱, 연속적이지 않은 인덱스 참조

In [ ]:
indices = torch.LongTensor([0,2])
describe(torch.index_select(x, dim=1, index=indices))

타입: torch.LongTensor
크기: torch.Size([2, 2])
값: 
tensor([[0, 2],
        [3, 5]])


In [ ]:
indices = torch.LongTensor([0, 0])
describe(torch.index_select(x, dim=0, index=indices))

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [ ]:
row_indices = torch.arange(2).long() # 인덱스는 LongTensor다. 파이토치 함수를 사용할 때 필수조건.
col_indices = torch.LongTensor([0,1])
describe(x[row_indices, col_indices])

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([0, 4])


### 텐서 연결

In [ ]:
import torch
x = torch.arange(6).view(2,3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
describe(torch.cat([x, x], dim=0)) # 연결

타입: torch.LongTensor
크기: torch.Size([4, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [ ]:
describe(torch.cat([x, x], dim=1))

타입: torch.LongTensor
크기: torch.Size([2, 6])
값: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [ ]:
describe(torch.stack([x,x]))

타입: torch.LongTensor
크기: torch.Size([2, 2, 3])
값: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


## 텐서 선형대수 연산

### 행렬 곱셈

In [ ]:
import torch
x1 = torch.arange(6).view(2, 3)
x1 = x1.float()
describe(x1)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [ ]:
x2 = torch.ones(3,2)
x2[:,1] += 1
describe(x2)

타입: torch.FloatTensor
크기: torch.Size([3, 2])
값: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [ ]:
describe(torch.mm(x1, x2))

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[ 3.,  6.],
        [12., 24.]])


## 텐서와 계산 그래프

파이토치 tensor 클래스는 데이터와 대수 연산, 인덱싱, 크기 변경 같은 다양한 연산을 캡슐화한다.

### 그레디언트 연산을 할 수 있는 텐서 만들기

텐서의 requires_grad 불리언 매개변수를 True로 지정하면 그레디언트 기반 학습에 필요한 손실 함수와 텐서의 그레디언트를 기록하는 부가 연산을 활성화한다.



In [ ]:
import torch
x = torch.ones(2,2, requires_grad=True)
describe(x)
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


requires_grad=True로 만들면 그레이디언트 계산에 사용하는 부가 정보를 관리한다.

먼저 파이토치가 정방향 계산의 값을 기록한다. 계산이 끝나면 스칼라값 하나를 사용해 역방향 계산을 수행한다.

In [ ]:
y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True


In [ ]:
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([])
값: 
21.0
False


역방향 계산은 손실 함수의 평가 결과로 얻은 텐서에서 backward() 메서드를 호출해 시작한다. 역방향 계산은 정방향 계산에 참여한 텐서 객체에 대한 그레이디언트 값을 계산한다.

## CUDA 텐서

지금까지는 텐서를 cpu 메모리에 할당했다. 
GPU가 있다면 선형 대수 연산을 수행할 때 되도록이면 사용하는 것이 좋다. 

GPU를 사용하려면 먼저 텐서를 GPU메모리에 할당해야 한다.

CUDA API를 사용해 GPU를 활용할 수 있다. (CUDA는 NVIDIA에서 만들었고 NVUDIA GPU에서만 사용된다.)

파이토치는 타입을 유지하면서 텐서를 CPU에서 GPU로 전송하여 CUDA 텐서를 매우 쉽게 만들 수 있다. 파이토치에서는 GPU나 CPU 같은 장치에 상관없이 동작하는 코드를 작성하는 것이 바람직하다. 그래서 torch.cuda.is_available()로 GPU를 사용할 수 있는지 확인하고 torch.device()로 장치 이름을 가져온 다음, to(device)로 모든 텐서를 타깃 장치로 이동한다.

In [ ]:
import torch
print(torch.cuda.is_available())

False


In [ ]:
# 바람직한 방법 : 장치에 무관한 텐서 초기화
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [ ]:
x = torch.rand(3, 3).to(device)
describe(x)

타입: torch.FloatTensor
크기: torch.Size([3, 3])
값: 
tensor([[0.6992, 0.8025, 0.0842],
        [0.5863, 0.8744, 0.3459],
        [0.3823, 0.9394, 0.1310]])


CUDA 텐서와 CUDA가 아닌 객체를 다루려면 두 객체가 같은 장치에 있어야 한다. 두 텐서 객체로 연산을 수행하다면 같은 장치에 있는지 확인하자. 

In [ ]:
y = torch.rand(3,3)
x + y

tensor([[1.5179, 1.3596, 0.6565],
        [1.2326, 1.5392, 1.1189],
        [1.1114, 1.4764, 1.0898]])

코랩에서는 cpu로만 해서 에러가 발생하지 않음.

GPU로 데이터를 넣고 꺼내는 작업은 비용이 많이 든다. 따라서 병렬 계산은 일반적으로 GPU에서 수행하고 최종 겨로가만 CPU로 전송하는 방식으로 이루어진다.